# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.game_board = QtWidgets.QTableWidget(self.centralwidget)
        self.game_board.setGeometry(QtCore.QRect(160, 280, 661, 541))
        self.game_board.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.game_board.setObjectName("game_board")
        self.game_board.setColumnCount(0)
        self.game_board.setRowCount(0)
        self.rb_left = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_left.setGeometry(QtCore.QRect(30, 290, 95, 20))
        self.rb_left.setObjectName("rb_left")
        self.rb_right = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_right.setGeometry(QtCore.QRect(30, 330, 95, 20))
        self.rb_right.setObjectName("rb_right")
        self.rb_up = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_up.setGeometry(QtCore.QRect(30, 370, 95, 20))
        self.rb_up.setObjectName("rb_up")
        self.rb_down = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_down.setGeometry(QtCore.QRect(30, 410, 95, 20))
        self.rb_down.setObjectName("rb_down")
        self.restart = QtWidgets.QPushButton(self.centralwidget)
        self.restart.setGeometry(QtCore.QRect(30, 470, 93, 28))
        self.restart.setObjectName("restart")
        self.label_2048 = QtWidgets.QLabel(self.centralwidget)
        self.label_2048.setGeometry(QtCore.QRect(400, 20, 200, 161))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2048.setFont(font)
        self.label_2048.setObjectName("label_2048")
        self.label_instructions = QtWidgets.QLabel(self.centralwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rb_left.setText(_translate("MainWindow", "Left"))
        self.rb_right.setText(_translate("MainWindow", "Right"))
        self.rb_up.setText(_translate("MainWindow", "Up"))
        self.rb_down.setText(_translate("MainWindow", "Down"))
        self.restart.setText(_translate("MainWindow", "Restart"))
        self.label_2048.setText(_translate("MainWindow", "2048"))
        self.label_instructions.setText(_translate("MainWindow", "Instructions:"))



